In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("quote_dataset.csv")

In [3]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [4]:
df.shape

(3038, 2)

In [5]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [6]:
quotes = quotes.str.lower()

In [7]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x : x.translate(translator))

In [8]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [11]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [12]:
sequence = tokenizer.texts_to_sequences(quotes)

In [13]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [14]:
sequence[0]

[713,
 62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461]

In [15]:
X = []
y= []
for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [16]:
X

[[713],
 [713, 62],
 [713, 62, 29],
 [713, 62, 29, 19],
 [713, 62, 29, 19, 16],
 [713, 62, 29, 19, 16, 946],
 [713, 62, 29, 19, 16, 946, 10],
 [713, 62, 29, 19, 16, 946, 10, 7],
 [713, 62, 29, 19, 16, 946, 10, 7, 5],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809],
 [713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752],
 [713,
  62,
  29,
  19,
  16,
  946,
  10,
  7,
  5,
  1156,
  8,
  70,
  293,
  10,
  145,
  12,
  809,
  104,
  752,
  70],
 [947],
 [947, 7],
 [947, 7, 70],
 [947, 7, 70, 871],
 [947, 7, 70, 871, 373],
 [947, 7, 70, 871, 373, 9],
 [947, 7, 70, 871, 373, 9, 433],
 [947, 7, 70, 871, 373, 9, 433, 21],
 [947, 7, 70, 871, 373, 9, 433, 21, 19],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54],
 [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70],
 [1337],
 [1337, 14],
 [1337, 14, 53],
 [1337, 14, 53, 201],
 [1337, 14, 53, 201, 714],
 [1337, 14, 53, 201, 714, 3],
 [1337, 14, 53, 201, 714, 3, 81],
 [1337, 14, 53, 201, 714, 3, 81, 15],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157],
 [1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7],
 [1337,
  14,
  53,
  201,
  714,
  3,
  81,
  15,
  36,
  37,
  7,
  29,
  329,
  93,
  7,
  5,
  1157,
  1,
  101,
  7,
  29,
  329,
  126,
  7,
  5],
 [713],
 [713, 116],
 [713, 116, 12],
 [713, 116, 12, 10],
 [713, 116, 12, 10, 2462],
 [713, 116, 12, 10, 2462, 32],
 [713, 116, 12, 10, 2462, 32, 1043],
 [713, 116, 12, 10, 2462, 32, 1043, 30],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119],
 [713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12],
 [713,
  116,
  12,
  10,
  2462,
  32,
  1043,
  30,
  82,
  13,
  601,
  11,
  5,
  74,
  1338,
  119,
  12,
  2463],
 [3679],
 [3679, 7],
 [3679, 7, 313],
 [3679, 7, 313, 753],
 [3679, 7, 313, 753, 7],
 [3679, 7, 313, 753, 7, 638],
 [3679, 7, 313, 753, 7, 638, 4],
 [3679, 7, 313, 753, 7, 638, 4, 43],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54],
 [3679, 7, 313, 753, 7, 638, 4, 43, 144, 3, 12, 682, 1339, 54, 682],
 [3681],
 [3681, 13],
 [3681, 13, 3],
 [3681, 13, 3, 202],
 [3681, 13, 3, 202, 5],
 [3681, 13, 3, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8],
 [3681, 13, 3, 202, 5, 90, 8, 434],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90],
 [3681, 13, 3, 202, 5, 90, 8, 434, 279, 202, 5, 90, 8],
 [947],
 [947, 7],
 [947, 7, 144],
 [947, 7, 144, 3],
 [947, 7, 144, 3, 12],
 [947, 7, 144, 3, 12, 1340],
 [947, 7, 144, 3, 12, 1340, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2],
 [947, 7, 144, 3, 12, 1340, 17, 21, 2, 14, 54, 3, 12, 175, 17, 21, 2, 14],
 [715],
 [715, 16],
 [715, 16, 13],
 [715, 16, 13, 1341],
 [715, 16, 13, 1341, 191],
 [715, 16, 13, 1341, 191, 51],
 [715, 16, 13, 1341, 191, 51, 415],
 [715, 16, 13, 1341, 191, 51, 415, 2464],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9],
 [715, 16, 13, 1341, 191, 51, 415, 2464, 714, 9, 363],
 [1044],
 [1044, 180],
 [1044, 180, 7],
 [1044, 180, 7, 39],
 [1044, 180, 7, 39, 5],
 [1044, 180, 7, 39, 5, 810],
 [1044, 180, 7, 39, 5, 810, 1342],
 [1044, 180, 7, 39, 5, 810, 1342, 2],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11],
 [1044, 180, 7, 39, 5, 810, 1342, 2, 46, 50, 59, 322, 10, 7, 168, 43, 11, 639],
 [1044],
 [1044, 111],
 [1044, 111, 104],
 [1044, 111, 104, 1045],
 [1044, 111, 104, 1045, 7],
 [1044, 111, 104, 1045, 7, 39],
 [1044, 111, 104, 1045, 7, 39, 2],
 [1044, 111, 104, 1045, 7, 39, 2, 50],
 [2465],
 [2465, 36],
 [2465, 36, 7],
 [2465, 36, 7, 21],
 [2465, 36, 7, 21, 2],
 [2465, 36, 7, 21, 2, 65],
 [2465, 36, 7, 21, 2, 65, 10],
 [2465, 36, 7, 21, 2, 65, 10, 47],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43],
 [2465, 36, 7, 21, 2, 65, 10, 47, 181, 21, 96, 130, 3, 754, 58, 123, 43, 5],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,
  74,
  208,
  7,
  2,
  94,
  3,
  466,
  59,
  96,
  130,
  3,
  754,
  10,
  58,
  516,
  28,
  12,
  15,
  212,
  948,
  517,
  39,
  10,
  811,
  18,
  51,
  158,
  89,
  132,
  89,
  79,
  1,
  234,
  9,
  271,
  22,
  2,
  146,
  126,
  272,
  15,
  161],
 [2465,
  36,
  7,
  21,
  2,
  65,
  10,
  47,
  181,
  21,
  96,
  130,
  3,
  754,
  58,
  123,
  43,
  5,
  1939,
  174,
  18,
  1,

In [17]:
y

[62,
 29,
 19,
 16,
 946,
 10,
 7,
 5,
 1156,
 8,
 70,
 293,
 10,
 145,
 12,
 809,
 104,
 752,
 70,
 2461,
 7,
 70,
 871,
 373,
 9,
 433,
 21,
 19,
 465,
 14,
 294,
 52,
 54,
 70,
 3676,
 14,
 53,
 201,
 714,
 3,
 81,
 15,
 36,
 37,
 7,
 29,
 329,
 93,
 7,
 5,
 1157,
 1,
 101,
 7,
 29,
 329,
 126,
 7,
 5,
 3677,
 116,
 12,
 10,
 2462,
 32,
 1043,
 30,
 82,
 13,
 601,
 11,
 5,
 74,
 1338,
 119,
 12,
 2463,
 3678,
 7,
 313,
 753,
 7,
 638,
 4,
 43,
 144,
 3,
 12,
 682,
 1339,
 54,
 682,
 3680,
 13,
 3,
 202,
 5,
 90,
 8,
 434,
 279,
 202,
 5,
 90,
 8,
 3682,
 7,
 144,
 3,
 12,
 1340,
 17,
 21,
 2,
 14,
 54,
 3,
 12,
 175,
 17,
 21,
 2,
 14,
 3683,
 16,
 13,
 1341,
 191,
 51,
 415,
 2464,
 714,
 9,
 363,
 3684,
 180,
 7,
 39,
 5,
 810,
 1342,
 2,
 46,
 50,
 59,
 322,
 10,
 7,
 168,
 43,
 11,
 639,
 3685,
 111,
 104,
 1045,
 7,
 39,
 2,
 50,
 3686,
 36,
 7,
 21,
 2,
 65,
 10,
 47,
 181,
 21,
 96,
 130,
 3,
 754,
 58,
 123,
 43,
 5,
 1939,
 174,
 18,
 1,
 74,
 208,
 7,
 2,
 94,
 3,
 466,
 59,
 96,
 130,
 3,
 754,
 10,
 58,
 516,
 28,
 12,
 15,
 212,
 948,
 517,
 39,
 10,
 811,
 18,
 51,
 158,
 89,
 132,
 89,
 79,
 1,
 234,
 9,
 271,
 22,
 2,
 146,
 126,
 272,
 15,
 161,
 159,
 212,
 49,
 102,
 79,
 8,
 48,
 389,
 158,
 2466,
 65,
 1,
 159,
 212,
 11,
 1,
 62,
 29,
 17,
 1343,
 167,
 948,
 132,
 4,
 79,
 85,
 4,
 812,
 6,
 273,
 3,
 118,
 10,
 117,
 8,
 48,
 482,
 416,
 105,
 23,
 8,
 48,
 14,
 130,
 3,
 390,
 15,
 92,
 18,
 2,
 140,
 133,
 58,
 55,
 20,
 2,
 133,
 58,
 237,
 46,
 113,
 15,
 2467,
 237,
 46,
 113,
 9,
 417,
 30,
 213,
 2,
 252,
 4,
 9,
 418,
 17,
 126,
 51,
 55,
 2,
 683,
 186,
 182,
 266,
 96,
 1046,
 683,
 44,
 126,
 176,
 260,
 343,
 42,
 4,
 69,
 69,
 69,
 127,
 11,
 100,
 55,
 20,
 2,
 49,
 86,
 30,
 28,
 2468,
 45,
 176,
 15,
 304,
 419,
 176,
 15,
 1570,
 58,
 4,
 117,
 1571,
 176,
 813,
 55,
 872,
 5,
 192,
 91,
 4,
 205,
 45,
 105,
 3,
 289,
 3687,
 344,
 5,
 151,
 640,
 8,
 873,
 3,
 314,
 58,
 3,
 70,
 755,
 18,
 51,
 29,
 105,
 3,
 314,
 58,
 3,
 70,
 3688,
 2,
 140,
 949,
 10,
 3,
 5,
 950,
 467,
 261,
 2,
 49,
 224,
 10,
 1940,
 134,
 13,
 12,
 77,
 178,
 77,
 262,
 32,
 77,
 53,
 76,
 175,
 183,
 76,
 134,
 24,
 170,
 18,
 20,
 76,
 225,
 2,
 147,
 21,
 171,
 602,
 574,
 13,
 2469,
 435,
 404,
 4,
 1,
 201,
 8,
 2,
 134,
 46,
 12,
 345,
 267,
 18,
 20,
 76,
 25,
 65,
 2,
 295,
 951,
 2,
 3,
 64,
 1049,
 4,
 952,
 3,
 128,
 187,
 4,
 354,
 391,
 343,
 953,
 77,
 4,
 133,
 77,
 1,
 117,
 2,
 25,
 76,
 134,
 13,
 12,
 293,
 66,
 2,
 87,
 452,
 8,
 1,
 111,
 18,
 76,
 28,
 133,
 2,
 5,
 208,
 8,
 77,
 9,
 76,
 274,
 2,
 25,
 2470,
 92,
 45,
 49,
 290,
 77,
 49,
 155,
 77,
 49,
 1941,
 4,
 49,
 453,
 52,
 54,
 76,
 25,
 133,
 289,
 27,
 76,
 213,
 2,
 193,
 102,
 77,
 50,
 27,
 76,
 213,
 2,
 436,
 4,
 575,
 77,
 27,
 574,
 13,
 3689,
 39,
 874,
 10,
 1572,
 58,
 1,
 814,
 1942,
 603,
 7,
 5,
 604,
 1943,
 11,
 3690,
 134,
 13,
 16,
 330,
 135,
 6,
 2471,
 3,
 79,
 18,
 6,
 64,
 6,
 16,
 1944,
 58,
 135,
 6,
 756,
 3,
 1945,
 815,
 8,
 24,
 7,
 13,
 273,
 43,
 816,
 1,
 815,
 8,
 495,
 7,
 13,
 1946,
 43,
 816,
 1,
 815,
 8,
 605,
 7,
 13,
 2472,
 43,
 816,
 4,
 1,
 815,
 8,
 36,
 7,
 13,
 214,
 43,
 3691,
 7,
 13,
 5,
 875,
 8,
 24,
 18,
 5,
 875,
 8,
 437,
 9,
 213,
 757,
 3692,
 212,
 74,
 114,
 4,
 5,
 2474,
 876,
 56,
 7,
 1,
 1573,
 3693,
 7,
 21,
 323,
 3,
 73,
 232,
 19,
 14,
 354,
 101,
 3694,
 24,
 2,
 104,
 364,
 59,
 32,
 27,
 32,
 68,
 135,
 6,
 24,
 2,
 576,
 104,
 817,
 32,
 877,
 6,
 24,
 2,
 11,
 56,
 78,
 55,
 6,
 31,
 13,
 50,
 148,
 101,
 78,
 8,
 392,
 18,
 56,
 11,
 120,
 40,
 7,
 47,
 6,
 32,
 2,
 45,
 1344,
 9,
 15,
 315,
 244,
 26,
 758,
 7,
 26,
 315,
 45,
 1344,
 9,
 27,
 6,
 228,
 684,
 15,
 222,
 3695,
 87,
 641,
 2,
 14,
 759,
 2,
 239,
 1948,
 1345,
 8,
 3697,
 2,
 716,
 41,
 2,
 16,
 47,
 67,
 3,
 24,
 3698,
 30,
 577,
 954,
 11,
 1574,
 25,
 65,
 2,
 5,
 1575,
 119,
 389,
 64,
 9,
 954,
 11,
 5,
 1949,
 25,
 65,
 2,
 5,
 3699,
 7,
 11,
 1,
 717,
 8,
 1,
 1576,
 4,
 10,
 134,
 12,
 604,
 68,
 67,
 3,
 67,
 3,
 133,
 5,
 346,
 32,
 1577,
 1576,
 5,
 468,
 3701,
 2,
 14,
 2,
 9,
 7,
 1950,
 54,
 161,
 40,
 7,
 47,
 37,
 393,
 30,
 7,
 2476,
 54,
 2477,
 2,
 57,
 15,
 347,
 3,
 12,
 578,
 124,
 48,
 685,
 686,
 20,
 2,
 57,
 48,
 3,
 12,
 52,
 578,
 124,
 48,
 52,
 685,
 3703,
 7,
 374,
 3,
 81,
 104,
 1578,
 44,
 83,
 469,
 2,
 81,
 45,
 2478,
 9,
 2,
 253,
 29,
 167,
 13,
 16,
 420,
 44,
 23,
 11,
 120,
 818,
 2,
 683,
 63,
 3704,
 28,
 94,
 2,
 68,
 5,
 3,
 1579,
 496,
 28,
 94,
 2,
 3706,
 74,
 91,
 66,
 305,
 27,
 10,
 1158,
 2,
 2,
 131,
 47,
 3708,
 52,
 9,
 2,
 124,
 1,
 52,
 61,
 2,
 28,
 50,
 1,
 52,
 9,
 2,
 203,
 1,
 52,
 642,
 237,
 3709,
 483,
 10,
 7,
 955,
 217,
 15,
 304,
 373,
 18,
 172,
 42,
 275,
 125,
 9,
 266,
 9,
 10,
 7,
 13,
 3711,
 174,
 7,
 235,
 7,
 130,
 3,
 290,
 2,
 2,
 51,
 206,
 3,
 113,
 1,
 234,
 331,
 405,
 3712,
 23,
 8,
 73,
 25,
 31,
 151,
 61,
 18,
 19,
 25,
 31,
 296,
 61,
 22,
 151,
 1951,
 1,
 2480,
 165,
 214,
 7,
 18,
 1,
 394,
 151,
 2481,
 2,
 164,
 7,
 24,
 18,
 5,
 139,
 1346,
 147,
 4,
 86,
 182,
 3714,
 124,
 3,
 50,
 88,
 13,
 3715,
 518,
 25,
 50,
 1,
 332,
 7,
 3,
 3717,
 16,
 69,
 1581,
 9,
 1582,
 28,
 12,
 5,
 194,
 8,
 2483,
 7,
 46,
 85,
 606,
 3,
 12,
 ...]

In [18]:
len(X)

85271

In [19]:
len(y)

85271

In [20]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [22]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [23]:
y = np.array(y)

In [24]:
X_padded.shape

(85271, 745)

In [25]:
y.shape

(85271,)

In [26]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y,num_classes = vocab_size)

In [27]:
y.shape

(85271,)

In [28]:
y_one_hot.shape

(85271, 10000)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, Dense

In [30]:
embedding_dim = 50
rnn_units = 128

In [31]:
rnn_model = Sequential()
rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)

)

rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [32]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [33]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [35]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [36]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
epochs = 10
batch_size = 128

In [38]:
history_rnn = rnn_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 46s 69ms/step - accuracy: 0.0447 - loss: 6.7161 - val_accuracy: 0.0576 - val_loss: 6.5625
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.0787 - loss: 6.1382 - val_accuracy: 0.0916 - val_loss: 6.3184
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1019 - loss: 5.7799 - val_accuracy: 0.0985 - val_loss: 6.2758
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1152 - loss: 5.4961 - val_accuracy: 0.1039 - val_loss: 6.3078
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 63ms/step - accuracy: 0.1266 - loss: 5.2517 - val_accuracy: 0.1095 - val_loss: 6.3562
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1386 - loss: 5.0251 - val_accuracy: 0.1087 - val_loss: 6.4165
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1525 - loss: 4.8101 - val_accuracy: 0.1113 - val_loss: 6.4562
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 39s 65ms/step - accuracy: 0.1689 - loss: 4.6071 - val_accuracy: 0.1092 - val_loss: 6.5403
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.1881 - loss: 4.4145 - val_accuracy: 0.1103 - val_loss: 6.5967
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 63ms/step - accuracy: 0.2085 - loss: 4.2313 - val_accuracy: 0.1092 - val_loss: 6.6689

In [39]:
epochs = 100
batch_size = 128

history_lstm = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.0391 - loss: 6.7614 - val_accuracy: 0.0466 - val_loss: 6.6762
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0565 - loss: 6.3310 - val_accuracy: 0.0598 - val_loss: 6.5790
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0770 - loss: 6.0797 - val_accuracy: 0.0836 - val_loss: 6.4780
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0952 - loss: 5.8619 - val_accuracy: 0.0952 - val_loss: 6.4281
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1064 - loss: 5.6802 - val_accuracy: 0.0979 - val_loss: 6.4253
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1162 - loss: 5.5107 - val_accuracy: 0.1048 - val_loss: 6.4324
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1252 - loss: 5.3521 - val_accuracy: 0.1078 - val_loss: 6.4504
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1331 - loss: 5.2046 - val_accuracy: 0.1074 - val_loss: 6.4892
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.1401 - loss: 5.0667 - val_accuracy: 0.1116 - val_loss: 6.5141
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1464 - loss: 4.9337 - val_accuracy: 0.1141 - val_loss: 6.5625
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1541 - loss: 4.8064 - val_accuracy: 0.1135 - val_loss: 6.6232
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1619 - loss: 4.6812 - val_accuracy: 0.1146 - val_loss: 6.6834
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1683 - loss: 4.5585 - val_accuracy: 0.1125 - val_loss: 6.7490
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1780 - loss: 4.4397 - val_accuracy: 0.1134 - val_loss: 6.8050
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1896 - loss: 4.3242 - val_accuracy: 0.1133 - val_loss: 6.8791
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2009 - loss: 4.2138 - val_accuracy: 0.1147 - val_loss: 6.9492
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2132 - loss: 4.1042 - val_accuracy: 0.1125 - val_loss: 7.0302
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2279 - loss: 4.0001 - val_accuracy: 0.1153 - val_loss: 7.1004
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2414 - loss: 3.9007 - val_accuracy: 0.1116 - val_loss: 7.1827
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2548 - loss: 3.8065 - val_accuracy: 0.1095 - val_loss: 7.2513
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2676 - loss: 3.7193 - val_accuracy: 0.1119 - val_loss: 7.3324
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2806 - loss: 3.6363 - val_accuracy: 0.1119 - val_loss: 7.4177
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2915 - loss: 3.5585 - val_accuracy: 0.1093 - val_loss: 7.4952
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3025 - loss: 3.4856 - val_accuracy: 0.1085 - val_loss: 7.5632
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3146 - loss: 3.4168 - val_accuracy: 0.1059 - val_loss: 7.6345
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3249 - loss: 3.3501 - val_accuracy: 0.1061 - val_loss: 7.6952
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3365 - loss: 3.2869 - val_accuracy: 0.1055 - val_loss: 7.7828
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3448 - loss: 3.2254 - val_accuracy: 0.1039 - val_loss: 7.8445
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3553 - loss: 3.1671 - val_accuracy: 0.1028 - val_loss: 7.9218
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3634 - loss: 3.1124 - val_accuracy: 0.1028 - val_loss: 7.9943
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3728 - loss: 3.0570 - val_accuracy: 0.1017 - val_loss: 8.0425
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3818 - loss: 3.0055 - val_accuracy: 0.1008 - val_loss: 8.1119
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.3907 - loss: 2.9549 - val_accuracy: 0.0998 - val_loss: 8.1769
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3986 - loss: 2.9055 - val_accuracy: 0.0967 - val_loss: 8.2358
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4069 - loss: 2.8584 - val_accuracy: 0.0971 - val_loss: 8.3049
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4158 - loss: 2.8115 - val_accuracy: 0.1011 - val_loss: 8.3691
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4232 - loss: 2.7660 - val_accuracy: 0.0959 - val_loss: 8.4212
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 55ms/step - accuracy: 0.4321 - loss: 2.7217 - val_accuracy: 0.0950 - val_loss: 8.4761
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4390 - loss: 2.6820 - val_accuracy: 0.0972 - val_loss: 8.5421
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.4463 - loss: 2.6388 - val_accuracy: 0.0953 - val_loss: 8.5971
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4543 - loss: 2.5976 - val_accuracy: 0.0951 - val_loss: 8.6624
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4611 - loss: 2.5581 - val_accuracy: 0.0949 - val_loss: 8.7280
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4686 - loss: 2.5205 - val_accuracy: 0.0952 - val_loss: 8.7613
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4760 - loss: 2.4821 - val_accuracy: 0.0939 - val_loss: 8.8189
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4828 - loss: 2.4466 - val_accuracy: 0.0916 - val_loss: 8.8911
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4879 - loss: 2.4107 - val_accuracy: 0.0953 - val_loss: 8.9577
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4945 - loss: 2.3767 - val_accuracy: 0.0931 - val_loss: 9.0110
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5005 - loss: 2.3423 - val_accuracy: 0.0899 - val_loss: 9.0804
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5068 - loss: 2.3100 - val_accuracy: 0.0905 - val_loss: 9.1171
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5128 - loss: 2.2772 - val_accuracy: 0.0890 - val_loss: 9.2013
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5189 - loss: 2.2454 - val_accuracy: 0.0894 - val_loss: 9.2576
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5250 - loss: 2.2145 - val_accuracy: 0.0896 - val_loss: 9.2962
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5304 - loss: 2.1847 - val_accuracy: 0.0906 - val_loss: 9.3470
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5371 - loss: 2.1550 - val_accuracy: 0.0889 - val_loss: 9.4070
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5416 - loss: 2.1263 - val_accuracy: 0.0881 - val_loss: 9.4612
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5476 - loss: 2.0981 - val_accuracy: 0.0865 - val_loss: 9.5297
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5517 - loss: 2.0710 - val_accuracy: 0.0869 - val_loss: 9.5658
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5584 - loss: 2.0431 - val_accuracy: 0.0864 - val_loss: 9.6159
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5639 - loss: 2.0168 - val_accuracy: 0.0841 - val_loss: 9.6727
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5679 - loss: 1.9912 - val_accuracy: 0.0848 - val_loss: 9.7382
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5739 - loss: 1.9663 - val_accuracy: 0.0850 - val_loss: 9.7952
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5784 - loss: 1.9429 - val_accuracy: 0.0848 - val_loss: 9.8234
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5837 - loss: 1.9182 - val_accuracy: 0.0851 - val_loss: 9.8821
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5881 - loss: 1.8929 - val_accuracy: 0.0842 - val_loss: 9.9400
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5915 - loss: 1.8690 - val_accuracy: 0.0823 - val_loss: 9.9990
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5981 - loss: 1.8468 - val_accuracy: 0.0833 - val_loss: 10.0428
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6020 - loss: 1.8237 - val_accuracy: 0.0840 - val_loss: 10.1040
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6055 - loss: 1.8053 - val_accuracy: 0.0838 - val_loss: 10.1553
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6108 - loss: 1.7806 - val_accuracy: 0.0822 - val_loss: 10.2005
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6144 - loss: 1.7594 - val_accuracy: 0.0806 - val_loss: 10.2625
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6188 - loss: 1.7379 - val_accuracy: 0.0833 - val_loss: 10.3140
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6241 - loss: 1.7178 - val_accuracy: 0.0815 - val_loss: 10.3550
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6274 - loss: 1.6982 - val_accuracy: 0.0816 - val_loss: 10.4167
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6311 - loss: 1.6793 - val_accuracy: 0.0815 - val_loss: 10.4526
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6357 - loss: 1.6594 - val_accuracy: 0.0799 - val_loss: 10.5068
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.6403 - loss: 1.6399 - val_accuracy: 0.0779 - val_loss: 10.5446
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6431 - loss: 1.6218 - val_accuracy: 0.0783 - val_loss: 10.6192
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6470 - loss: 1.6048 - val_accuracy: 0.0803 - val_loss: 10.6870
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6506 - loss: 1.5865 - val_accuracy: 0.0784 - val_loss: 10.7086
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6545 - loss: 1.5678 - val_accuracy: 0.0796 - val_loss: 10.7675
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6578 - loss: 1.5512 - val_accuracy: 0.0786 - val_loss: 10.7968
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6623 - loss: 1.5327 - val_accuracy: 0.0799 - val_loss: 10.8566
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6648 - loss: 1.5170 - val_accuracy: 0.0796 - val_loss: 10.8946
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6690 - loss: 1.5004 - val_accuracy: 0.0775 - val_loss: 10.9502
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6724 - loss: 1.4841 - val_accuracy: 0.0786 - val_loss: 11.0020
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6756 - loss: 1.4685 - val_accuracy: 0.0784 - val_loss: 11.0442
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6782 - loss: 1.4540 - val_accuracy: 0.0795 - val_loss: 11.0766
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6835 - loss: 1.4371 - val_accuracy: 0.0776 - val_loss: 11.1337
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6854 - loss: 1.4241 - val_accuracy: 0.0784 - val_loss: 11.1695
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6873 - loss: 1.4090 - val_accuracy: 0.0773 - val_loss: 11.2391
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6912 - loss: 1.3945 - val_accuracy: 0.0768 - val_loss: 11.2576
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6958 - loss: 1.3801 - val_accuracy: 0.0790 - val_loss: 11.3321
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6975 - loss: 1.3649 - val_accuracy: 0.0792 - val_loss: 11.3824
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6997 - loss: 1.3524 - val_accuracy: 0.0774 - val_loss: 11.4310
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7034 - loss: 1.3379 - val_accuracy: 0.0763 - val_loss: 11.4697
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7072 - loss: 1.3247 - val_accuracy: 0.0783 - val_loss: 11.5358
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7100 - loss: 1.3117 - val_accuracy: 0.0741 - val_loss: 11.5670
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7121 - loss: 1.2992 - val_accuracy: 0.0782 - val_loss: 11.5963
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.7152 - loss: 1.2865 - val_accuracy: 0.0742 - val_loss: 11.6496
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7175 - loss: 1.2739 - val_accuracy: 0.0758 - val_loss: 11.6848

In [40]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [41]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [42]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
def predictor(model, tokenizer,text, max_len):
  text= text.lower()
  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')
  pred = model.predict(seq, verbose=0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [51]:
seed_text = "what"
next_word = predictor(lstm_model, tokenizer, seed_text, max_len)
print(next_word)

you

In [58]:
def generate_text(model, tokenizer, seed_text, max_len, num_words):
  for _ in range(num_words):
    next_word = predictor(model, tokenizer, seed_text, max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [59]:
seed = "are a"
generate_text = generate_text(lstm_model, tokenizer, seed, max_len, 10)
print(generate_text)

are a life in a grain of ten friends some drop of

In [62]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [63]:
with open("tmax_len.pkl", "wb") as f:
  pickle.dump(max_len, f)